Clarify usage

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -52,9 +52,39 @@ backup_and_push() {
 }
 
 usage() {
-  echo "$@" >&2
+  echo "$0" >&2
+  echo "Error: $@" >&2
+  cat >&2 <<EOF
+
+Launch a backup of our databases
+The following environment variables must be defined:
+
+PGP_KEYS: The public keys for which we must encrypt the backup
+
+ADDON_ID_<db_name>=<addon_id> : the name of the db to backup and its addon id
+  An ADDON_ID_<db_name> must be defined for each addon to backup
+
+AWS_ACCESS_KEY_ID: authentication information for target S3 bucket
+AWS_SECRET_ACCESS_KEY: authentication information for target S3 bucket
+
+S3_URL: an s3:// url for the target bucket to where to store the backup
+S3_HOST_BUCKET: configuration of target S3 system
+  may look like this: '%(bucket)s.cellar-c2.services.clever-cloud.com'
+
+CLEVER_SECRET: authentication information to download add-on backup
+CLEVER_TOKEN: authentication information to download add-on backup
+
+EOF
   exit 1
 }
+
+[[ -z "${PGP_KEYS+x}"              ]] && usage "You must define PGP_KEYS"
+[[ -z "${S3_URL+x}"                ]] && usage "You must define S3_URL"
+[[ -z "${S3_HOST_BUCKET+x}"        ]] && usage "You must define S3_HOST_BUCKET"
+[[ -z "${AWS_ACCESS_KEY_ID+x}"     ]] && usage "You must define AWS_ACCESS_KEY_ID"
+[[ -z "${AWS_SECRET_ACCESS_KEY+x}" ]] && usage "You must define AWS_SECRET_ACCESS_KEY"
+[[ -z "${CLEVER_SECRET+x}"         ]] && usage "You must define CLEVER_SECRET"
+[[ -z "${CLEVER_TOKEN+x}"          ]] && usage "You must define CLEVER_TOKEN"
 
 if ! set | grep '^ADDON_ID_' >/dev/null
 then
